theme: jekyll-theme-slate
title: Médialab BAnQ
description: Une plateforme de type médialab.
organisation_repos_url: https://github.com/medialab-banq/
show_downloads: false
google_analytics: UA-12469043-29
gems:
  - jekyll-octicons
