theme: jekyll-theme-slate
title: Médialab BAnQ
description: Plateforme de partage numérique du médialab crée par Bibliothèque et Archives nationales du Québec.
organisation_repos_url: https://github.com/medialab-banq/
show_downloads: false
google_analytics: UA-12469043-29
gems:
  - jekyll-octicons
